blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import PostCreateView, PostListView, PostDetailView, PostUpdateView, PostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', PostListView.as_view(), name='list'),
    path('create/', PostCreateView.as_view(), name='create'),
    path('read/<int:pk>/', PostDetailView.as_view(), name='read'),
    path('update/<int:pk>/', PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='delete'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', )),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


NULLABLE = {'null': True, 'blank': True}

class Post(models.Model):
    title = models.CharField(max_length=100, verbose_name='Загловок')
    slug = models.CharField(max_length=100, verbose_name='ЧПУ', **NULLABLE)
    content = models.TextField(verbose_name='Текст')
    image = models.ImageField(upload_to='blog/', verbose_name='Изображение', **NULLABLE)
    create_date = models.DateTimeField(default=timezone.now, verbose_name='Дата создания')
    published = models.BooleanField(default=True, verbose_name='Статус публикации')
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return {self.title}\

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Post


class PostCreateView(CreateView):
    model = Post
    fields = ('title', 'content', 'image',)
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.title)
            new_post.save()

        return super().form_valid(form)

class PostUpdateView(UpdateView):
    model = Post
    fields = ('title', 'content', 'image',)
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.title)
            new_post.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:read', args=[self.kwargs.get('pk')])

class PostListView(ListView):
    model = Post

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(published=True)
        return queryset

class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:list')

blog/templates/blog/post_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>{% extends 'catalog/base.html' %}

{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить пост {{ object.title }}?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'blog:list' %}">Отказаться</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags_filtres %}


{% block content %}
<div class="container">
    <div class="row text-center">


        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h1 class="my-0 font-weight-normal">{{ object.title | title }}</h1>
                </div>
                <div class="card-body">
                    <p>Человеко-понятный УРЛ: {{ object.slug }}</p>
                    <p>Описание: {{ object.content }}</p>
                    <p><img src="{% mediapath object.image %}" width="200px"></p>
                    <p>Дата создания: {{ object.create_date }}</p>
                    <p>Количество просмотров: {{ object.views_count }}</p>
                    <a href="{% url 'blog:update' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Редактировать</a>
                    <a href="{% url 'blog:delete' object.pk %}" type="button" class="btn btn-sm btn-outline-danger">Удалить</a>

                </div>
            </div>
        </div>


    </div>
</div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'catalog/base.html' %}


{% block content %}
<div class="container">
    <a href="{% url 'blog:create' %}" type="button" class="btn btn-sm btn-outline-secondary">Создать новый пост</a>
    <div class="row text-center">
        {% for object in object_list %}

        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h1 class="card-title pricing-card-title">{{ object.title | title }}</h1></div>
                <div class="card-body">

                    <p>{{ object.content | slice:":100" }}</p>
                    <a href="{% url 'blog:read' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Открыть</a>
                    <a href="{% url 'blog:update' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Редактировать</a>
                    <a href="{% url 'blog:delete' object.pk %}" type="button" class="btn btn-sm btn-outline-danger">Удалить</a>
                    <p>{{ object.views_count }}</p>


                </div>
            </div>
        </div>

        {% endfor %}

    </div>
</div>
{% endblock %}